### ISSUE TITLE
TypeError: a bytes-like object is required, not 'ZipExtFile' on Python 3.5

### ISSUE THREAD

**Issue by bzamecnik** [bzamecnik/s3dt-catalog#5]
Works on Python 3.4, does not work on Python 3.5.

```
 tasks.update_ed_catalog() from default
bcd3570c-4724-4d58-b8db-b95d888f87e8
Failed 3 minutes ago
Traceback (most recent call last):
  File "/home/bza/anaconda3/envs/s3dt_catalog/lib/python3.5/site-packages/xmltodict.py", line 246, in parse
    parser.ParseFile(xml_input)
  File "/home/bza/anaconda3/envs/s3dt_catalog/lib/python3.5/zipfile.py", line 844, in read
    data = self._read1(n)
  File "/home/bza/anaconda3/envs/s3dt_catalog/lib/python3.5/zipfile.py", line 912, in _read1
    data += self._read2(n - len(data))
  File "/home/bza/anaconda3/envs/s3dt_catalog/lib/python3.5/zipfile.py", line 944, in _read2
    data = self._fileobj.read(n)
  File "/home/bza/anaconda3/envs/s3dt_catalog/lib/python3.5/zipfile.py", line 662, in read
    self._file.seek(self._pos)
AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bza/anaconda3/envs/s3dt_catalog/lib/python3.5/site-packages/rq/worker.py", line 557, in perform_job
    rv = job.perform()
  File "/home/bza/anaconda3/envs/s3dt_catalog/lib/python3.5/site-packages/rq/job.py", line 492, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/home/bza/services/s3dt-catalog/tasks.py", line 32, in update_ed_catalog
    download_ed_catalog_to_mongo(mongo_uri, catalog_url, counter)
  File "/home/bza/services/s3dt-catalog/ed_catalog.py", line 182, in download_ed_catalog_to_mongo
    load_catalog_to_mongo(catalog_xml, item_collection, counter)
  File "/home/bza/services/s3dt-catalog/ed_catalog.py", line 79, in load_catalog_to_mongo
    process_catalog(input_xml, process_item)
  File "/home/bza/services/s3dt-catalog/ed_catalog.py", line 53, in process_catalog
    xmltodict.parse(input_xml, item_depth=3, item_callback=handle_item)
  File "/home/bza/anaconda3/envs/s3dt_catalog/lib/python3.5/site-packages/xmltodict.py", line 248, in parse
    parser.Parse(xml_input, True)
TypeError: a bytes-like object is required, not 'ZipExtFile'
```
